name: check

on:
  pull_request:
    branch: ['*', '!main']
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.0.2
          run_install: true

      - name: Dependencies install
        run: pnpm install

      - name: Run test
        run: pnpm test

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run eslint
        run: pnpm lint

      - name: Run prettier
        run: pnpm format

      - name: Run build
        run: pnpm build
