name: check

on:
  pull_request:
    branch: ['*', '!main']
  jobs:
    check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Cache node modules
          uses: actions/cache@v2
          env:
            cache-name: cache-node-modules
            with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                ${{ runner.os }}-

        - uses: pnpm/action-setup@v2.1.0
          with:
            version: 6.0.2
            run_install: true

        - name: Dependencies install
          run: pnpm install

        - name: Run typecheck
          run: pnpm typecheck

        - name: Run eslint
          run: pnpm lint

        - name: Run prettier
          run: pnpm format

        - name: Run build
          run: pnpm build
